require('plugins/plugins_config/bufferline')
require('plugins/plugins_config/lualine')
require('plugins/plugins_config/tree')
require('plugins/plugins_config/treesitter')
require('plugins/plugins_config/web-devicons')
